
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:  # Allow this workflow to be called from other workflows, e.g. publish.yml

jobs:
  test:
    name: Python ${{ matrix.python}} ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install tox coverage

      - name: Run tox targets for Python ${{ matrix.python }}
        run: |
          # Run only the tox environments that match the Python version
          tox run -f py$(echo ${{ matrix.python }} | tr -d .)
