
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

# Current configuration:
# - django 4.2, python 3.9, wagtail 5.2, postgres
# - django 5.0, python 3.10, wagtail 6.0, sqlite
# - django 5.1, python 3.11, wagtail 6.1, postgres
# - django 5.1, python 3.12, wagtail 6.2, sqlite
# - django 5.1, python 3.12, wagtail 6.3, postgres
# - django 5.2, python 3.13, wagtail 6.4, sqlite
# - django 5.2, python 3.13, wagtail main, sqlite (allow failures)
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - python: "3.9"
            django: "Django>=4.2,<4.3"
            wagtail: "wagtail>=5.2,<5.3"
            database: "postgresql"
            experimental: false
          - python: "3.10"
            django: "Django>=5.0,<5.1"
            wagtail: "wagtail>=6.0,<6.1"
            database: "sqlite3"
            experimental: false
          - python: "3.11"
            django: "Django>=5.1,<5.2"
            wagtail: "wagtail>=6.1,<6.2"
            database: "postgresql"
            experimental: false
          - python: "3.12"
            django: "Django>=5.1,<5.2"
            wagtail: "wagtail>=6.2,<6.3"
            database: "sqlite3"
            experimental: false
          - python: "3.12"
            django: "Django>=5.1,<5.2"
            wagtail: "wagtail>=6.3,<6.4"
            database: "postgresql"
            experimental: false
          - python: "3.13"
            django: "Django>=5.2,<5.3"
            wagtail: "wagtail>=6.4,<6.5"
            database: "sqlite3"
            experimental: false

          - python: "3.13"
            django: "Django>=5.2,<5.3"
            wagtail: "git+https://github.com/wagtail/wagtail.git@main#egg=wagtail"
            database: "sqlite3"
            experimental: true

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "psycopg>=3.1.8"
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
          pip install -e .
      - name: Test
        run: ./runtests.py
        env:
          DATABASE_ENGINE: django.db.backends.${{ matrix.database }}
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
